package com.example.myapplication.model

data class Exercise(
    val name: String,
    val durationSeconds: Int
)

object WorkoutRepository {
    fun getExercises(): List<Exercise> {
        return listOf(
            Exercise("Aufwärmen", 140),
            Exercise("Dumbbell Squats", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Squats", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Squats", 40),
            Exercise("Pause", 60),
            Exercise("Calf raises", 40),
            Exercise("Pause", 20),
            Exercise("Calf raises", 40),
            Exercise("Pause", 20),
            Exercise("Calf raises", 40),
            Exercise("Pause", 60),
            Exercise("Dumbbell Pushups", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Pushups", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Pushups", 40),
            Exercise("Pause", 60),
            Exercise("Military Press", 40),
            Exercise("Pause", 20),
            Exercise("Military Press", 40),
            Exercise("Pause", 20),
            Exercise("Military Press", 40),
            Exercise("Pause", 60),
            Exercise("Dumbbell Bench Press", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Bench Press", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Bench Press", 40),
            Exercise("Pause", 60),
            Exercise("Triceps Curls", 40),
            Exercise("Pause", 20),
            Exercise("Triceps Curls", 40),
            Exercise("Pause", 20),
            Exercise("Triceps Curls", 40),
            Exercise("Pause", 60),
            Exercise("Dumbbell Glute Bridge", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Glute Bridge", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Glute Bridge", 40),
            Exercise("Pause", 60),
            Exercise("Dumbbell Rows (right)", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Rows (right)", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Rows (right)", 40),
            Exercise("Pause", 60),
            Exercise("Dumbbell Rows (left)", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Rows (left)", 40),
            Exercise("Pause", 20),
            Exercise("Dumbbell Rows (left)", 40),
            Exercise("Pause", 60),
            Exercise("Scotman Curls", 40),
            Exercise("Pause", 20),
            Exercise("Scotman Curls", 40),
            Exercise("Pause", 20),
            Exercise("Scotman Curls", 40),
            Exercise("Pause", 60),
            Exercise("Biceps Curls", 40),
            Exercise("Pause", 20),
            Exercise("Biceps Curls", 40),
            Exercise("Pause", 20),
            Exercise("Biceps Curls", 40),
            Exercise("Pause", 60),
            Exercise("Shoulder Press", 40),
            Exercise("Pause", 20),
            Exercise("Shoulder Press", 40),
            Exercise("Pause", 20),
            Exercise("Shoulder Press", 40),
            Exercise("Pause", 60),
            Exercise("Reverse Fly", 40),
            Exercise("Pause", 20),
            Exercise("Reverse Fly", 40),
            Exercise("Pause", 20),
            Exercise("Reverse Fly", 40),
            Exercise("Pause", 60),
            Exercise("Leg Raises", 40),
            Exercise("Pause", 20),
            Exercise("Flutter Kicks", 40),
            Exercise("Pause", 20),
            Exercise("Toe Touches", 40),
            Exercise("Pause", 20),
            Exercise("Bicycle Crunches", 40),
            Exercise("Pause", 20),
            Exercise("Heel Touches", 40),
            Exercise("Pause", 20),
            Exercise("Dead Bug", 40),
            Exercise("Pause", 20),
            Exercise("Hollow Body Hold", 40),
            Exercise("Pause", 20),
            Exercise("Toe Touch Hold", 40),
            Exercise("Pause", 20),
            Exercise("Plank", 50),
            Exercise("Pause", 20),
            Exercise("Mountain Climbers", 50),
        )
    }
}
